django_project/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path(r'users/', include(('users.urls', 'users'), namespace='users')),
    path(r'', include(('learning_logs.urls', 'learning_logs'), namespace='learning_logs')),
    path(r'', include(('rest_app.urls', 'rest_app'), namespace='rest_app')),
]

learning_logs/urls.py
from django.urls import path
from django.views.generic import TemplateView

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('topics/', views.topics, name='topics'),
    path('topics/<topic_id>/', views.topic, name='topic'),
    path('new_topic/', views.new_topic, name='new_topic'),
    path('new_entry/<topic_id>/', views.new_entry, name='new_entry'),
    path('edit_entry/<entry_id>/', views.edit_entry, name='edit_entry'),

]

rest_app/urls.py
from django.urls import path
from django.views.generic import TemplateView
from rest_app.views import restListView, restDetailView

urlpatterns = [
    path('rest_app/', TemplateView.as_view(template_name='rest_app/rest_app.html'), name='rest_app'),
    path('rest_app/api/request', restListView.as_view()),
    path('rest_app/api/request/<pk>', restDetailView.as_view()),
]

users/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from django.views.generic import TemplateView
from . import views

urlpatterns = [
    path('login/', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('register/', views.register, name='register'),
    path('articles/', views.articles, name='articles'),
    path('articles/<article_id>/', views.article, name='article'),
    path('friends', views.friends, name='friends'),
    path('add_friend/<friend_id>/', views.add_friend, name='add_friend'),
    path('friend_added', views.friend_added, name='friend_added'),
    path('delete_friend/<friend_id>/', views.delete_friend, name='delete_friend'),
    path('friend_deleted', views.friend_deleted, name='friend_deleted'),

]

learning_logs/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Topic(models.Model):
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.DO_NOTHING)

    def __str__(self):
        return self.text

class Entry(models.Model):
    topic = models.ForeignKey(Topic, on_delete=models.DO_NOTHING)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'entries'

    def __str__(self):
        return self.text[:50] + "..."

learning_logs/forms.py
from django import forms
from.models import Topic, Entry

class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['text']
        labels = {'text': ''}

class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text': ''}
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}

learning_logs/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, Http404
from .models import Topic, Entry
from .forms import TopicForm, EntryForm

from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required


# Create your views here.

def index(request):
    #home page
    return render(request, 'learning_logs/index.html')

@login_required
def topics(request):
    #display Topics
    topics = Topic.objects.filter(owner=request.user).order_by('date_added')
    context = {'topics': topics}
    return render(request, 'learning_logs/topics.html', context)

@login_required
def topic(request, topic_id):
    #display topic and all its content
    topic = Topic.objects.get(id=topic_id)

    #check topic ownership
    if topic.owner != request.user:
        raise Http404

    entries = topic.entry_set.order_by('-date_added')
    context = {'topic': topic, 'entries':entries}
    return render(request, 'learning_logs/topic.html', context)

@login_required
def new_topic(request):
    if request.method != 'POST':
        #create empty form
        form = TopicForm()
    else:
        form = TopicForm(data=request.POST)
        if form.is_valid():
            new_topic = form.save(commit=False)
            new_topic.owner = request.user
            new_topic.save()
            return HttpResponseRedirect(reverse('learning_logs:topics'))
    context = {'form': form}
    return render(request, 'learning_logs/new_topic.html', context)

@login_required
def new_entry(request, topic_id):
    topic = Topic.objects.get(id=topic_id)

    if request.method != 'POST':
        form = EntryForm()
    else:
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.save()
            return HttpResponseRedirect(reverse('learning_logs:topic', args=[topic_id]))

    context = {'topic': topic, 'form': form}
    return render(request, 'learning_logs/new_entry.html', context)

@login_required
def edit_entry(request, entry_id):
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic

    # check topic ownership
    if topic.owner != request.user:
        raise Http404

    if request.method != 'POST':
        form = EntryForm(instance=entry)
    else:
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('learning_logs:topic', args=[topic.id]))

    context = {'entry': entry, 'topic': topic, 'form': form}
    return render(request, 'learning_logs/edit_entry.html', context)

learning_logs/templates/learning_logs/base.html
<p>
   <a href="{% url 'learning_logs:index' %}">Home page</a> -
    <a href="{% url 'learning_logs:topics' %}">Topics</a> -
    <a href="{% url 'users:friends' %}">Friends</a> -
    <a href="{% url 'rest_app:rest_app' %}">REST</a> -
    {% if user.is_authenticated %}
    Hello {{ user.username }}.
    <a href="{% url 'users:logout' %}">Log out</a>
    {% else %}
    <a href="{% url 'users:login' %}">Log in</a> -
    <a href="{% url 'users:register' %}">Register</a>
    {% endif %}
    </p>
{% block content %} {% endblock content %}

learning_logs/templates/learning_logs/edit_entry.html
{% extends "learning_logs/base.html" %}

{% block content %}

<p><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></p>

<p>Edit entry:</p>
<form action="{% url 'learning_logs:edit_entry' entry.id %}" method='post'>
    {% csrf_token %}
    {{ form.as_p }}
    <button name="submit">save changes</button>
</form>

{% endblock content %}

learning_logs/templates/learning_logs/index.html
{% extends "learning_logs/base.html" %}

{% block content %}
<p>Learning Django</p>
<p>Learning Django is for learning duh</p>
{% endblock content %}

learning_logs/templates/learning_logs/new_entry.html
{% extends "learning_logs/base.html" %}

{% block content %}

<p><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></p>

<p>Add a new entry:</p>
<form action="{% url 'learning_logs:new_entry' topic.id %}" method='post'>
    {% csrf_token %}
    {{ form.as_p }}
    <button name="submit">add entry</button>
</form>

{% endblock content %}

learning_logs/templates/learning_logs/new_topic.html
{% extends "learning_logs/base.html" %}

{% block content %}

<p>Add New topic</p>

<form action="{% url 'learning_logs:new_topic' %}" method='post'>
    {% csrf_token%}
    {{ form.as_p }}
    <button name="submit">add topic</button>
</form>

{% endblock content %}

learning_logs/templates/learning_logs/topic.html
{% extends "learning_logs/base.html" %}

{% block content %}

<p>Topic: {{ topic }}</p>

<p>Entries:</p>
<p>
    <a href="{% url 'learning_logs:new_entry' topic.id %}">Add new entry</a>
</p>
<ul>
    {% for entry in entries %}
        <li>
            <p>{{ entry.date_added|date:'M d, Y H:i' }}</p>
            <p>{{ entry.text|linebreaks }}</p>
            <p> <a href="{% url 'learning_logs:edit_entry' entry.id %}">edit entry</a> </p>
        </li>
    {% empty %}
        <li>No entries yet</li>
    {% endfor %}
</ul>

{% endblock content %}

learning_logs/templates/learning_logs/topics.html
{% extends "learning_logs/base.html" %}

{% block content %}

<p>Topics</p>

<ul>
    {% for topic in topics %}
        <li>
            <a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }} </a>
        </li>
    {% empty %}
        <li>No topics yet</li>
    {% endfor %}
</ul>

<a href="{% url 'learning_logs:new_topic' %}"> Add New topic </a>

{% endblock content %}