django_project/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path(r'users/', include(('users.urls', 'users'), namespace='users')),
    path(r'', include(('learning_logs.urls', 'learning_logs'), namespace='learning_logs')),
    path(r'', include(('rest_app.urls', 'rest_app'), namespace='rest_app')),
]

learning_logs/urls.py
from django.urls import path
from django.views.generic import TemplateView

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('topics/', views.topics, name='topics'),
    path('topics/<topic_id>/', views.topic, name='topic'),
    path('new_topic/', views.new_topic, name='new_topic'),
    path('new_entry/<topic_id>/', views.new_entry, name='new_entry'),
    path('edit_entry/<entry_id>/', views.edit_entry, name='edit_entry'),

]

users/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from django.views.generic import TemplateView
from . import views

urlpatterns = [
    path('login/', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('register/', views.register, name='register'),
    path('articles/', views.articles, name='articles'),
    path('articles/<article_id>/', views.article, name='article'),
    path('friends', views.friends, name='friends'),
    path('add_friend/<friend_id>/', views.add_friend, name='add_friend'),
    path('friend_added', views.friend_added, name='friend_added'),
    path('delete_friend/<friend_id>/', views.delete_friend, name='delete_friend'),
    path('friend_deleted', views.friend_deleted, name='friend_deleted'),

]

users/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

#Many to many examples

class Article(models.Model):
    title = models.CharField(max_length=10)
    authors = models.ManyToManyField('Author', through='Written_by')

    def __str__(self):
        return self.title

class Author(models.Model):
    name = models.CharField(max_length=10)
    articles = models.ManyToManyField('Article', through='Written_by')

    def __str__(self):
        return self.name

class Written_by(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    author = models.ForeignKey(Author, on_delete=models.CASCADE)

    class Meta:
        verbose_name_plural = 'Written by'

class Friend(models.Model):
    users = models.ManyToManyField(User)
    current_user = models.ForeignKey(User, related_name='owner', on_delete=models.DO_NOTHING)

    @classmethod
    def add_friend(cls, current_user, new_friend):
        friend, created = cls.objects.get_or_create(current_user=current_user)
        friend.users.add(new_friend)

    @classmethod
    def delete_friend(cls, current_user, old_friend):
        friend, created = cls.objects.get_or_create(current_user=current_user)
        friend.users.remove(old_friend)

users/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from django.contrib.auth import logout, login, authenticate
from django.urls import reverse
from django.contrib.auth.forms import UserCreationForm
from .models import Article, Friend
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required

# Create your views here.

# custom logout, not used
def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse('learning_logs:index'))

def register(request):
    if request.method != 'POST':
        form = UserCreationForm()
    else:
        form = UserCreationForm(data=request.POST)

        if form.is_valid():
            new_user = form.save()
            authenticaded_user = authenticate(username=new_user.username, password=request.POST['password1'])
            login(request, authenticaded_user)
            return HttpResponseRedirect(reverse('learning_logs:index'))
    context = {'form': form}
    return render(request, 'users/register.html', context)

def articles(request):
    articles = Article.objects.all()
    context = {'articles': articles}
    return render(request, 'users/articles.html', context)

def article(request, article_id):
    article = Article.objects.get(id=article_id)
    authors = article
    context = {'article': article, 'authors': authors}
    return render(request, 'users/article.html', context)

@login_required
def friends(request):
    users = User.objects.all()
    friend = Friend.objects.get(current_user=request.user)
    friends = friend.users.all()
    context = {'friends': friends, 'users': users}
    return render(request, 'users/friends.html', context)

@login_required
def add_friend(request, friend_id):
    new_friend = User.objects.get(pk=friend_id)
    Friend.add_friend(request.user, new_friend)
    return render(request, 'users/friend_added.html')

def friend_added(request):
    return render(request, 'users/friend_added.html')

@login_required
def delete_friend(request, friend_id):
    old_friend = User.objects.get(pk=friend_id)
    Friend.delete_friend(request.user, old_friend)
    return render(request, 'users/friend_deleted.html')

def friend_deleted(request):
    return render(request, 'users/friend_deleted.html')

users/templates/users/Login.html
{% extends "learning_logs/base.html" %}

{% block content %}

{% if form.errors %}
<p>Error in login</p>
{% endif %}

<form method="post" action="{% url 'users:login' %}">
    {% csrf_token %}
    {{ form.as_p }}

    <button name="submit">log in</button>
    <input type="hidden" name="next" value="{% url 'learning_logs:index' %}" />
</form>

{% endblock content %}

users/templates/users/Logout.html
{% extends "learning_logs/base.html" %}

{% block content %}
<p> Log out succesfull </p>
{% endblock content %}

users/templates/users/Register.html
{% extends "learning_logs/base.html" %}
{% block content %}

<form method="post" action="{% url 'users:register' %}">
    {% csrf_token %}
    {{ form.as_p }}

    <button name="submit">register</button>
    <input type="hidden" name="next" value="{% url 'learning_logs:index' %}" />
</form>

{% endblock content %}

users/templates/users/about.html
{% extends "learning_logs/base.html" %}

{% block content %}
<p> About </p>
{% endblock content %}

users/templates/users/article.html
{% extends "learning_logs/base.html" %}

{% block content %}

<p>Article {{ article }}</p>

<p>Authors:</p>

<ul>
    {% for author in authors %}
        <li>
            <p>{{ author.name|linebreaks }}</p>
        </li>
    {% empty %}
        <li>No authors</li>
    {% endfor %}
</ul>

{% endblock content %}

users/templates/users/articles.html
{% extends "learning_logs/base.html" %}

{% block content %}

<p>Articles</p>

<ul>
    {% for article in articles %}
        <li>
            <a href="{% url 'users:articles' %}">{{ article }} </a>
        </li>
    {% empty %}
        <li>No articles yet</li>
    {% endfor %}
</ul>

{% endblock content %}

users/templates/users/friend_added.html
{% extends "learning_logs/base.html" %}

{% block content %}

<p>Friend was successfully added!</p>

{% endblock content %}

users/templates/users/friend_deleted.html
{% extends "learning_logs/base.html" %}

{% block content %}

<p>Friend was successfully deleted :(</p>

{% endblock content %}

users/templates/users/friends.html
{% extends "learning_logs/base.html" %}

{% block content %}

<title>Friends and Users</title>

<p>Users:</p>
<ul>
    {% for user in users %}
        <li>
            <a href="{% url 'users:add_friend' user.id %}">{{ user }} </a>
        </li>
    {% empty %}
        <li>No users yet</li>
    {% endfor %}
</ul>

<p>Friends:</p>
<ul>
    {% for friend in friends %}
        <li>
            <a href="{% url 'users:delete_friend' friend.id %}">{{ friend }} </a>
        </li>
    {% empty %}
        <li>No friends yet</li>
    {% endfor %}
</ul>

{% endblock content %}